version: '3.8'

services:
  publish-and-consume-rabbitmq:
    container_name: publish-and-consume-rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:3.7.14-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
  publish-and-consume-mongo:
    container_name: publish-and-consume-mongo
    platform: linux/amd64
    image: mongo:4.4
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./data/mongo:/data
