// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/short-url": {
            "post": {
                "description": "Short URL",
                "summary": "Short URL",
                "parameters": [
                    {
                        "description": "URL to short",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully processed transcriptions",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error during processing",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    }
                }
            }
        },
        "/{id}": {
            "get": {
                "description": "Redirect",
                "summary": "Redirect",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully processed transcriptions",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error during processing",
                        "schema": {
                            "$ref": "#/definitions/urlshort.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "urlshort.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "shortenedUrl": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Transcription Service API",
	Description:      "Pulish data to RabbitMQ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
