definitions:
  urlshort.PublishToQueueBody:
    properties:
      username:
        type: string
    type: object
  urlshort.Response:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Publish and Consume with RabbitMQ and MongoDB
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Publish and Consume
  version: "1.0"
paths:
  /:
    post:
      description: Publish to queue
      parameters:
      - description: Publish to queue body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/urlshort.PublishToQueueBody'
      responses:
        "200":
          description: Successfully published to queue
          schema:
            $ref: '#/definitions/urlshort.Response'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/urlshort.Response'
        "500":
          description: Internal server error during processing
          schema:
            $ref: '#/definitions/urlshort.Response'
      summary: Publish to queue
swagger: "2.0"
